### ISSUE TITLE
process for getting into CBRAIN

### ISSUE THREAD

**Issue by gkiar** [margulies/surfaceanalysis#1]
- [x] make sure the `surfaceanalysis.py`script runs
- [x] make sure the command-line in your `descriptor.json` matches the command-line for the script
- [x] make sure the parameter descriptions in your `descriptor.json` still match the parameters (i.e. if you changed the command-line, make sure to make necessary changes to the corresponding objects accordingly, such as changing a "String" to a "File", etc...)
- [x] build a Docker image from your `Dockerfile` with `docker build -t margulies/surfaceanalysis:dev .`
- [x] launch Docker container and run your tool from within Docker, with `docker run -ti -v ${path-to-my-data}:${path-to-my-data} -w ${path-to-my-data} --entrypoint /bin/bash margulies/surfacenalaysis:dev`, and then type `${path-to-my-script} ${all-command-line-args}` to verify it runs.

N.B. every time I write `${something-in-these-brackets}` I mean to substitute this value with whatever it MEANS in your particular case, i.e. `${path-to-my-data}` may be `/data`, etc.

**Comment by margulies** [comment]
Done!
